### ISSUE TITLE
New modification form doesn't allow to change section

### ISSUE THREAD

**Issue by leio10** [podemos-info/national_budgets#19]
![imagen](https://user-images.githubusercontent.com/453545/65860446-a2454d00-e36a-11e9-8fde-8cae29db889f.png)

**Comment by joseluispodemos** [comment]
This was fixed with this commit https://github.com/podemos-info/national_budgets/pull/18/commits/43c7310e2c6af0ee569f11919e5086419ca71a69

**Comment by joseluispodemos** [comment]
Fixed here 😅  https://github.com/podemos-info/national_budgets/pull/22/commits/0206e2965f334a51698f25512a908bf64d20f1d4
